export const AUTH_SCREEN = 'Authentication'
export const PROFILE = 'Profile'
export const DASHBOARD = 'Dashboard'
export const MY_FILES = 'MyFiles'
export const SETTINGS = 'Settings'
export const LIBRARY = 'Library'
export const EDIT_PROFILE = 'EditProfile'
export const WORD_READER = 'WordReader'
